### ISSUE TITLE
失效了，是不是以后都不能用hosts了

### ISSUE THREAD

**Issue by cero-ss** [Leakless/pixiv-hosts#3]
下午的时候发现失效了，试了下其他hosts都不行，是不是以后改hosts都不行了呢

**Comment by Leakless** [comment]
也许是吧。tg上看到的消息是已经开始tls识别了，在服务器端没有支持ESNI的前提下改hosts只能说是螳臂当车。

**Comment by embeddedsecurity** [comment]
@Leakless 
![11111111111111](https://user-images.githubusercontent.com/24518756/47602079-feda1280-da0b-11e8-8732-b5b69d3c5ea1.jpg)
改完HOSTS怎么刷新DNS缓存都没用.ESNI什么时候能大规模部署？谷歌ESNI开始大规模部署了吗？

**Comment by Leakless** [comment]
> @Leakless
> ![11111111111111](https://user-images.githubusercontent.com/24518756/47602079-feda1280-da0b-11e8-8732-b5b69d3c5ea1.jpg)
> 改完HOSTS怎么刷新DNS缓存都没用.ESNI什么时候能大规模部署？谷歌ESNI开始大规模部署了吗？

摊手，谁知道呢
